### ISSUE TITLE
Analysis of existing offline tool

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#124]
**Describe the Task**
Analysis of existing spatial offline tool @popkinj

**Comment by popkinj** [comment]
I'm glad I had another look at this one @ZoeSimon .
Turns out the two existing offline plugins for Leaflet; [offline](https://github.com/allartk/leaflet.offline) and the [pouchdb one](https://github.com/MazeMap/Leaflet.TileLayer.PouchDBCached) only support TMS services... Which are typically used in Basemap layers. Like the BCGov and ESRI basemaps.

So I think we have two options
1. Enhance our existing plugin to also accept WMS layers
1. Spin up a [MapProxy](https://mapproxy.org/) server that will do the conversion WMS->TMS for us.

I'm leaning towards the later of the two options because we would gain some advantages:
1. Faster layers
1. Layer level security
1. We won't have to figure out someone else's plugin code.
