### ISSUE TITLE
Caching Layers/Pull in warehouse accessible layers to app

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#125]
**Describe the Task**
As per ticket #811, the a user would needs the ability to cache layers to work offline other than the data they are making themselves.
 
**Acceptance Criteria**
- [ ] cache page to allow for creating 1 cache environment 
- [ ] consider possibly 3 cache areas (optional)
- [ ] cache page to provide total space available field
- [ ] cache page to provide total used space available field
- [ ] allow user to define an area or use the current map area as the cache frame 
- [ ] allow the user to erase the local cache
- [ ] default layers (see mock up)
    - Default Layers that were left off the mock-up but need to be added:
       - [ ] First Nations Reserves
       - [ ] Imagery (ESRI)
- [ ] optional layers (see mock up)
    - Optional Layers that were left off the mock-up but need to be added:
       - [ ] WMUs
       - [ ] Freshwater atlas

**Pull in warehouse accessible layers to mobile app:**

- [ ]  Regional Districts and Municipalities (worked on by Freshworks)
- [ ]  Well sites (worked on by Freshworks)
- [ ]  Natural Resource Districts
- [ ]  MOTI Regions / Districts
- [ ]  BEC layers
- [ ]  RISO boundaries
- [ ]  IPMA (invasive plant management areas)
- [ ]  Wildlife Management Units
- [ ]  Legal and Proposed GAR Designation
  - [ ]  Ungulate Winter Range
  - [ ]  Fisheries Sensitive Watershed
  - [ ]  Wildlife Habitat Areas
- [ ]  Old Growth Management Areas
- [ ]  Freshwater Atlas (FWA)
  - [ ]  Streams
  - [ ]  Lakes, wetlands, manmade waterbodies
  - [ ]  Major rivers
  - [ ]  Obstructions
- [ ]  Ownership Layers
- [ ]  FN Reserves
- [ ]  Provincial Parks
  - [ ]  Ecological Reserves
  - [ ]  Protected Areas
  - [ ]  Recreation Areas
  - [ ]  Conservation Areas
- [ ]  National Parks

**Comment by popkinj** [comment]
I'm glad I had another look at this one @ZoeSimon .
Turns out the two existing offline plugins for Leaflet; [offline](https://github.com/allartk/leaflet.offline) and the [pouchdb one](https://github.com/MazeMap/Leaflet.TileLayer.PouchDBCached) only support TMS services... Which are typically used in Basemap layers. Like the BCGov and ESRI basemaps.

So I think we have two options
1. Enhance our existing plugin to also accept WMS layers
1. Spin up a [MapProxy](https://mapproxy.org/) or [Geoserver](http://geoserver.org/) server that will do the conversion WMS->TMS for us.

I'm leaning towards the later of the two options because we would gain some advantages:
1. Faster layers
1. Layer level security
1. We won't have to figure out someone else's plugin code.

**Comment by ZoeSimon** [comment]
Broken down into ticket #347 #348 #351 #352 #353

**Comment by ZoeSimon** [comment]
MOTI RFI Layer & Gravel pit layer (most important for MOTI - more so than regions) @popkinj @ZoeSimon

**Comment by popkinj** [comment]
Got it. Thanks.

**Comment by ZoeSimon** [comment]
FSRs addition @mikeshasko @popkinj
