### ISSUE TITLE
activity layer colour consistency (clusters, donuts)

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#2372]
- [ ] activity cluster colours match to record categories

**Comment by chrisrafusetech** [comment]
Working on colour consistency, and not sure what is the single source of truth and activity type Geo feature colour.  

For example there are 2 monitoring areas, different colours and boundary filter area in blue.
<img width="705" alt="2 Monitoring, 1 Boundary Filter" src="https://user-images.githubusercontent.com/117766863/208989432-cb465618-1022-48cb-a457-06afcaef3061.png">
Questions, Why different colours for monitoring areas, by design, mech. vs chem monitoring? or is bug? or need to fix(me/other)?  
What am I looking at for the monitoring areas? are these makers or feature polygons? 
Now do I need to change these colours to SLD style color(see below) and/or fix the reason why they are all different?
The same activity type colour is consistent to all zoom levels and donut pieces correspond to the correct colour?

I have sourced the activity type colours from SLD(map/SldStyles/invasivesbc_sld.js) to apply the following colours to the donut graph of activity types and percentage.  
<img width="1236" alt="DonutShop2" src="https://user-images.githubusercontent.com/117766863/209033828-9a23d70a-d416-4c83-acce-71e95b22e84a.png">
Notice label is behind the donut.
Question, I am using the colours specified from the SLD and matching colours to all markers or geo bounds for that activity type colour?
```
  const activityPallete = {
    Biocontrol : '#845ec2',
    FREP: '#de852c',
    Monitoring: '#2138e0',
    Observation: '#399c3e',
    Treatment: '#c6c617'
  };
```
Color_Biocontrol_845ec2
<img width="705" alt="Color_Biocontrol_845ec2" src="https://user-images.githubusercontent.com/117766863/208988295-1ee37887-0e2a-406c-bac8-bb0b3f161067.png">
Color_FREP_de852c
<img width="705" alt="Color_FREP_de852c" src="https://user-images.githubusercontent.com/117766863/208988284-6c041e84-ab73-492c-a0a4-2c263e1af88b.png">
Color_Monitoring_2138e0
<img width="705" alt="Color_Monitoring_2138e0" src="https://user-images.githubusercontent.com/117766863/208988293-a9d3670c-70c0-40ce-84a2-7ae3b1eaf05f.png">
Color_Observation_eb9e34
<img width="715" alt="Color_Observation_399c3e" src="https://user-images.githubusercontent.com/117766863/209032419-89e3ae48-e066-445d-9e3b-63c9e176f2f0.png">
Color_Treatment_c6c617
<img width="705" alt="Color_Treatment_c6c617" src="https://user-images.githubusercontent.com/117766863/208988278-674d5b39-7391-43ca-8061-a7102a7703a3.png">

**Comment by brennanwebster** [comment]
Questions, Why different colours for monitoring areas, by design, mech. vs chem monitoring? or is bug? or need to fix(me/other)?

**The different colours for monitorings is by design. Biocontrol monitoring being purple like the other biocontrol activities makes more sense from the IP staffs perspective. Chemical and Mechanical treatment monitorings are blue I believe.**


What am I looking at for the monitoring areas? are these makers or feature polygons?

**I think the polygons are from the GeoJSONMemo in ActivitiesLayerV2.**


Now do I need to change these colours to SLD style color(see below) and/or fix the reason why they are all different?

**I think the colour for the donut markers should be the same as the sld/polygon colours. Biocontrol purple, Observation green, Treatment yellow, Chem/Mech monitoring blue.**


The same activity type colour is consistent to all zoom levels and donut pieces correspond to the correct colour?

**Yes.**


Question, I am using the colours specified from the SLD and matching colours to all markers or geo bounds for that activity type colour?

**Yes, although I think the geo bounding polygon that shows when you hover over a donut marker can stay blue.**

**Comment by micheal-w-wells** [comment]
What I did to make the markers different colours for the leaflet canvas marker component was to just use different coloured png.  It is technically possible to use css filtering on icons to change their colour, might even be an example in git history of this repo somewhere -  but I wouldn't worry about it for now.

I'd do stuff in this order:

- [ ] Access the mapping of record type to colour, ideally from the sld style object so updates Brennan makes are reflected later
- [ ] Donuts using the colours
- [ ] Donut colour matches label, not count
- [ ] with all that done, see if you can get marker colours to match, easiest way is get a palatte of pins to pull from.

I agree with Brennan the bounds colour doesn't need to change.

**Comment by chrisrafusetech** [comment]
Error on colour that was set for Observations in the above colour set.  Updated the images above with correct colours from SLD for the dounut.  This is just a preview of the front-end colours used. 
To set the activity type colours from the SLD, I will need to build a fillColor object from cycling/filtering through the items from the SLDParser.readStyle to grab the fillColor property.  OR copy and paste these values to the donut.
Now label, I assume, but I shouldn't, that the 6 Observations is the label and that should match the color of the donut slice or activity type colour?

**Comment by chrisrafusetech** [comment]
<img width="1061" alt="ErrorOnPurpleMonitoringRecord" src="https://user-images.githubusercontent.com/117766863/209053061-78ea6aff-4e26-4b77-a3b0-ab7f2437268f.png">
Maybe why it was showing purple for a monitoring activity in the top image.
