### ISSUE TITLE
Feb 9 user testing issues

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#2440]
- [x] Advanced filter for recordsets cancels out other column filters (until you click save and apply filters)
- [x] Issues with suggested jurisdiction not having expected result (ie. MOF suggested for a provincial park, need to experiment a bit with this one)
- [x] Copy paste form data works, but many drop down fields appear to be empty (they actually aren't) after paste

**Comment by micheal-w-wells** [comment]
Due to how expensive some queries can be (and in spite of how cheap some are), we can't have 'search as you type' which is why you need to hit save after changing grid filters.  

Example of expensive query that would blow up on typing - spatial boundary + species, and user types letters into another field like jurisdiction.

For this ticket, the advanced filters had a bug where they would update the search critiria, ignoring grid filters, and trigger a save.  I've changed this so that they too require hitting save, however you can just hit save once (change grid filters, add advanced filters and hit save).

Can we solve that one day and let people see the results change as they type? Yes.  Today?  Not enough time unfortunately.

The other boxes- the MOF thing was a code table issue, and Gabe fixed copy paste which was only partially refactored during the cutover to redux-saga.
