### ISSUE TITLE
white screen between form types

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#2832]
When opening an observation records after having a chem treatment record open there is an undefined area on the PMP validation.

**Comment by micheal-w-wells** [comment]
For whoever is gonna work on it:

This happens because the fetch for the activity to load in to state is not done before the user navigated to the activity page, so the old record type components are still mounted.

I would do it like this:  on firing 'activity_get_request' we block opening the record (on the button and tab) until  the success message fires.  

A new state variable 'activity_loading' can be used for this, and set in the reducer when either of those 2 actions fires (no new actions needed).  Point the button and tab to this variable.  

Easier to do in the new template, in the old one the whole app will rerender basically if you mess with the tab state.
