### ISSUE TITLE
IAPP Migration for existing media (iapp photos)

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#320]
- [ ] figure out how to make photos attached to IAPP sites viewable when online in InvasivesBC
- [ ] Figure out how to make photos attached to IAPP sites viewable for records you have cached when offline.

Someone with access to the code is needed that puts the photos in the iapp database to help me with the 2 lines to decode it, we tried using javascript and never got a photo we could see

**Comment by ghost** [comment]
Question:  I have a table column that is used to store a jpg image.  How do I extract a jpg image file from inside an Oracle table?

Answer:  You can use Oracle BLOB data types to store photographs and images in jpg, gif, tif, eps, mov, mp3 or any other format that you desire, it does not matter to a large binary column.  However, you cannot use standard SQL to retrieve an image from an Oracle table, you need a PL/SQL procedure, like this one.

For more information on PL/SQL tips and tricks, I recommend Dr. Hall's book "PL/SQL Tuning Secrets", a great source of working PL/SQL code examples:

Retrieve a jpg photograph from Oracle:

DECLARE
t_blob BLOB;
t_len NUMBER;
t_file_name VARCHAR2(100);
t_output UTL_FILE.file_type;
t_TotalSize number;
t_position number := 1;
t_chucklen NUMBER := 4096;
t_chuck raw(4096);
t_remain number;
BEGIN
-- Get length of blob
SELECT DBMS_LOB.getlength (PHOTO), ename || '_1.jpg'
INTO t_TotalSize, t_file_name FROM DEMO WHERE ENAME ='moon';
t_remain := t_TotalSize;
-- The directory TEMPDIR should exist before executing
t_output := UTL_FILE.fopen ('TEMPDIR', t_file_name, 'wb', 32760);
-- Get BLOB
SELECT PHOTO INTO t_blob FROM DEMO WHERE ENAME ='moon';
-- Retrieving BLOB
WHILE t_position < t_TotalSize
LOOP
DBMS_LOB.READ (t_blob, t_chucklen, t_position, t_chuck);
UTL_FILE.put_raw (t_output, t_chuck);
UTL_FILE.fflush (t_output);
t_position := t_position + t_chucklen;
t_remain := t_remain - t_chucklen;
IF t_remain < 4096
THEN
t_chucklen := t_remain;
END IF;
END LOOP;
END;

**Comment by dogcomplex** [comment]
Tried to decode the CSV data from these through various means (mostly trying to use browser tools or online converter sites) but no luck getting those to actual images.  Might need more info on how these images were originally uploaded to the database (e.g. is there a pre-conversion? Is there enforcement of a particular filetype - are they all JPEG?).  The current encoding appears to be "application/octet-stream" rather than Base64, if that helps at all, but that still wasnt enough to get viewable images for me yet.

Happy to take a deeper look at this, but yeah - initial attempts no luck.  If there's more info on the original process for encoding these, that'd certainly help.

**Comment by ZoeSimon** [comment]
Re-visit this ticket when higher value tasks are completed.
@mikeshasko as per our discussion

**Comment by CrystalChadburn** [comment]
@micheal-w-wells  now that we got you access into the IAPP code, I'm hoping we could assign someone to make this happen?

**Comment by CrystalChadburn** [comment]
@brennanwebster can you please give @plasticviking admin access to IAPP

**Comment by brennanwebster** [comment]
Okay done.

**Comment by plasticviking** [comment]
still stalled pending DB access
