### ISSUE TITLE
Geo autofill fields error

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#3504]
Geo autofill fields all show "is a required field" even though they are filled out (happens on both web and mobile)

**Comment by LocalNewsTV** [comment]
## Additional Details
Bug is only visual, but inconvenient for users due to misleading error text.

If you add a value, an error displays showing the geographical data is invalid. 
If you trigger a re-render of the form via `Save Menu`, the re-render will remove the error and keep your entered data.
