### ISSUE TITLE
Mobile: Crash when filtering recordset

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#3509]
While online and filtering InvasivesBC recordset for invasive plant the app crashed. Happened multiple times, no error was shown, the app just restarts

Note: typing in the filter box is also slow for some reason

**Comment by LocalNewsTV** [comment]
Typing in the filter box is slow since it makes new API requests with the updated data. 

@plasticviking maybe we could decouple the filters to at least an onBlur/Enter press. While I'm in there the filtering could use a UI overhaul too. Two birds one stone. We can make that a separate ticket if you find it fitting. The decoupling would at least add a performance boost so that area.
