### ISSUE TITLE
Chemical Treatment record page edits 

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#695]
# simple ones first:
- [x] Add new 'Treatment Organization' field before first Pesticide Applicator name field.
- [x] Change the name of the field "pesticide applicator number" to be "Service License Number".  Drop down remains the same.
- [x] if wind is 0, there should be no direction chosen.  Ideally auto fill no direction if 0 is chosen, at minimum show an error at sync if user choses anything other than no direction.
- [x] Pest Management Plan field needs to have options to choose from drop down, enter a number manually, OR choose "n/a". (#695 )
- [x] Fix typo in herbicide code table for milestone

**Comment by micheal-w-wells** [comment]
# tackle these after (maybe separate issue)
- [ ] Add UTMs as well as lat/longs, or if only one can be there, should be UTMs. (also in 607).
- [ ] Temperature and wind and herbicide values need to have an "are you sure" pop up warning instead of a red box forcing you to lie.  If the user clicks "yes" that they are sure, then they can be allowed to add something outside of the acceptable range.
- [ ] Pesticide User License field should be autofilled based on log-in (attached to user entering IDIR or BCeID) and then autofilled.  Doesn't need to be on form, but needs to be recorded upon syncing/submitting record.
